# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

test:
  script:
    - hugo version
  except:
    - master
