baseURL = "/"
languageCode = "en-us"
title = "Snorre Lothar von Gohren Edwin"
theme = "coder"

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

[params] # theme parameters
    author = "Snorre Lothar von Gohren Edwin" # Author's name.
    info = "Kiting Full Stack blockchainer with a dose DevOps" # Author's job title or info.
    description = "Snorre Lothar von Gohren Edwin's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/profile.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Welcome, do as you please, contact me if you want" # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/vongohren/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/vongohren/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/vongohren/"

# Menu links
[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "/projects/"
[[menu.main]]
    name = "Talks"
    weight = 1
    url  = "/talks/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
